# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: tailor | your | BIM 
company: © 2022 Chings e.U.
companyurl: "http://chings.eu"
header: ./assets/img/logotyb.png
email: info@tailoryourbim.com
author: Ching
description: >- # this means to ignore newlines until "baseurl:"
  Got wishes for an improved BIM workflow and environment?
  Make all your efforts for planing projects, let us tailor your BIM to meet your needs.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://tailoryourbim.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: tailoryourbim
github_username: tailoryourbim
linkedin_username: tailoryourbim

permalink: /:categories/:title/

# Build settings
markdown: kramdown
theme: minima
#remote_theme: jekyll/minima
remote_theme: pages-themes/dinky@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  #- jekyll-remote-theme

#google_analytics: UA-216043528-1
google_analytics: G-5QTTTRNC1H

defaults: 
  - scope:
      path: "/assets/img/"
    values:
      image: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/ 
#   - vendor/gems/
#   - vendor/ruby/

# theme dinky
show_downloads: true
